### ISSUE TITLE
An issue with spots pr

### ISSUE THREAD

**Issue by JDOG787** [JDOG787/JDOG787#19]
@spotandjake You can't use `position: fixed;` for the cursor.

**Comment by spotandjake** [comment]
it is not on the cursor it is on a container arround the cursor. i make a container so that i deal with the overflow issue the container sizes to the screen and is position fixed as it doesnt need to move i tested it and it is working fine.

**Comment by spotandjake** [comment]
use dev tools to take a look at it

**Comment by JDOG787** [comment]
yes, but it doesn't work on pages that scroll(projects page)

**Comment by JDOG787** [comment]
go to https://jdog.codes/work

**Comment by JDOG787** [comment]
go to https://jdog.codes/work

**Comment by JDOG787** [comment]
go to [jdog.codes](https://jdog.codes/work)
