### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by zghwi** [JDOG787/JDOG787#9]
You have a typo in your readme
You wrote relp.it instead of repl.it but the url is fine

**Comment by JDOG787** [comment]
Huh, I thought I fixed that, but restarting my website must have reverted the fix somehow, thanks

**Comment by zghwi** [comment]
oh yeah no problem :)))
also I would like to contribute to pictoshare :)
sorry if I told you before, but yeah you got the idea

**Comment by zghwi** [comment]
what was pictoshare bootstraped with?
can you tell me?

**Comment by JDOG787** [comment]
> oh yeah no problem :)))
> also I would like to contribute to pictoshare :)
> sorry if I told you before, but yeah you got the idea

Sure, I’ve been taking a little break from deving it, but you can still contribute.

**Comment by JDOG787** [comment]
> what was pictoshare bootstraped with?
> can you tell me?

Wdym bootstrapped?

**Comment by zghwi** [comment]
i mean like `create-next-app --templaet any-ts-template` or `npx create-react-app --template typescript`
what template you have used with pictoshare?

**Comment by JDOG787** [comment]
i think i used typescript

**Comment by zghwi** [comment]
Oh cool, what is the command?

**Comment by JDOG787** [comment]
`npm run dev`

**Comment by zghwi** [comment]
bruh that's not what i want, i know how to start a development server
let's just close this issue kthxbai

**Comment by JDOG787** [comment]
Ok lol
